"""Invisible generator watermarks.

Stability AI's reference code, and the Hugging Face diffusers pipelines built
on it, embed an invisible DWT-DCT watermark in every image by default:
"StableDiffusionV1" (Stable Diffusion 1.x), "SDV2" (2.x) and a fixed 48-bit
message (SDXL). Finding one is strong evidence the image came from those
models. Not finding one proves nothing: many front-ends switch it off, and
resizing or recompression destroys it.

The decoder is a numpy re-implementation of the `dwtDct` method in the
MIT-licensed invisible-watermark package (imwatermark.maxDct), checked bit
for bit against it. That package also pulls in PyTorch for a method not
used here, so it isn't a dependency.
"""

from __future__ import annotations

import numpy as np
from scipy.stats import binom

from ..result import AI, INFO, NOTABLE, Result

KEY = "watermark"
TITLE = "Invisible generator watermarks"
GUIDE = ("Looks for the invisible watermarks Stable Diffusion's reference code embeds. A match is strong evidence of "
         "AI generation; no match proves nothing, since the watermark is often disabled and doesn't survive "
         "resizing or heavy recompression.")

SDXL_BITS = [int(b) for b in bin(0b101100111110110010010000011110111011000110011110)[2:]]
CANDIDATES = [
    ("Stable Diffusion 1.x", "bytes", b"StableDiffusionV1"),
    ("Stable Diffusion 2.x", "bytes", b"SDV2"),
    ("Stable Diffusion XL", "bits", SDXL_BITS),
]


def _bits(value) -> np.ndarray:
    if isinstance(value, (bytes, bytearray)):
        return np.unpackbits(np.frombuffer(bytes(value), dtype=np.uint8))
    return np.asarray(value, dtype=np.uint8)


def _u_channel(bgr: np.ndarray) -> np.ndarray:
    """OpenCV's COLOR_BGR2YUV U channel for 8-bit input, in its exact
    fixed-point arithmetic (so decoding matches the reference bit for bit)."""
    b, g, r = (bgr[..., i].astype(np.int64) for i in range(3))
    y = (b * 1868 + g * 9617 + r * 4899 + 8192) >> 14
    return np.clip(((b - y) * 8061 + (128 << 14) + 8192) >> 14, 0, 255).astype(np.float64)


def decode_bits(bgr: np.ndarray, length: int, scale: float = 36.0, block: int = 4) -> np.ndarray:
    """The dwtDct decoder: Haar approximation of the U channel, 4×4 blocks in
    raster order, and in each block the largest AC coefficient's magnitude
    modulo `scale` gives one vote for bit (block index mod length)."""
    rows, cols = bgr.shape[0] // 4 * 4, bgr.shape[1] // 4 * 4
    u = _u_channel(bgr[:rows, :cols])
    # pywt.dwt2(..., "haar") approximation, computed the way PyWavelets does
    # it (filter 1/√2, vertical pass then horizontal). Coefficients often land
    # exactly on the decision threshold, so the rounding has to match too.
    h = 0.7071067811865476
    v = u[1::2, :] * h + u[0::2, :] * h
    ca = v[:, 1::2] * h + v[:, 0::2] * h
    br, bc = ca.shape[0] // block, ca.shape[1] // block
    blocks = ca[: br * block, : bc * block].reshape(br, block, bc, block).swapaxes(1, 2).reshape(-1, block * block)
    pos = np.argmax(np.abs(blocks[:, 1:]), axis=1) + 1
    val = np.abs(blocks[np.arange(len(blocks)), pos])
    votes = (np.mod(val, scale) > 0.5 * scale).astype(np.float64)
    idx = np.arange(len(blocks)) % length
    avg = np.bincount(idx, weights=votes, minlength=length) / np.maximum(np.bincount(idx, minlength=length), 1)
    return (avg * 255 > 127).astype(np.uint8)


def detect(rgb: np.ndarray) -> list[dict]:
    found = []
    for name, _kind, message in CANDIDATES:
        expected = _bits(message)
        n = expected.size
        # Reference scripts pass BGR (OpenCV) images; diffusers passes RGB.
        best = min(float(np.mean(decode_bits(order, n) != expected)) for order in (rgb[..., ::-1], rgb))
        errors = int(round(best * n))
        # Chance of matching this well at random (a binomial tail), corrected
        # for the six decodes tried (three watermarks × two channel orders).
        p = min(1.0, float(binom.cdf(errors, n, 0.5)) * 6)
        found.append({"model": name, "bits": n, "bit_error_rate": round(best, 4), "p_value": p, "match": p < 1e-6})
    return found


def run(ex, settings) -> Result:
    res = Result(KEY, TITLE, AI, GUIDE)
    if min(ex.width, ex.height) < 256:
        res.skipped = "image too small"
        return res
    results = detect(ex.rgb)
    res.metrics = {"candidates": results}
    hits = [r for r in results if r["match"]]
    for h in hits:
        res.add(NOTABLE, f"Invisible watermark: {h['model']}",
                f"The image carries the invisible watermark Stability AI's {h['model']} reference code embeds "
                f"({(1 - h['bit_error_rate']) * 100:.0f}% of {h['bits']} bits match; the chance of that at random is "
                f"about {h['p_value']:.0e}). That is strong evidence it was generated by that model.")
    if not hits:
        res.add(INFO, "No known invisible watermark",
                "None of the Stable Diffusion watermarks were found. That doesn't show the image is real: most "
                "generators don't use them, resizing or recompression removes them, and the scheme can't be read "
                "back reliably even from untouched dark or low-detail images.")
    return res
